### ISSUE TITLE
Flashed OTA and no root anymore

### ISSUE THREAD

**Issue by jordanss1** [chenxiaolong/avbroot#413]
Hi, not sure why but after flashing OTA as normal I went into the Magisk app, chose to restart to do extra configuration and also updated the app inside the Magisk app (not flashing Magisk itself). Now my phone says I don't have root. Even though I did everything according to the guide and how I normally do it. Am I going to have to wipe hard reset and start from scratch or is there something I can finesse to get it working? I find it hard to believe root is just gone like that.

**Comment by pixincreate** [comment]
can you do `adb root` from your pc?

this is bound to happen if you're on grapheneos.

**Comment by jordanss1** [comment]
With usb debugging on for some reason my computer says

> ADB server didn't ACK
Full server startup log: /tmp/adb.1000.log
Server had pid: 30220
--- adb starting (pid 30220) ---
02-02 14:47:39.384 30220 30220 I adb     : main.cpp:63 Android Debug Bridge version 1.0.41
02-02 14:47:39.384 30220 30220 I adb     : main.cpp:63 Version 35.0.2-12147458
02-02 14:47:39.384 30220 30220 I adb     : main.cpp:63 Running on Linux 6.8.0-52-generic (x86_64)
02-02 14:47:39.384 30220 30220 I adb     : main.cpp:63 
02-02 14:47:39.385 30220 30220 I adb     : auth.cpp:416 adb_auth_init...
02-02 14:47:39.385 30220 30220 I adb     : auth.cpp:391 adb_auth_inotify_init...
02-02 14:47:39.386 30220 30220 I adb     : udp_socket.cpp:170 AdbUdpSocket fd=12
02-02 14:47:39.386 30220 30220 I adb     : udp_socket.cpp:170 AdbUdpSocket fd=16
02-02 14:47:39.386 30220 30220 I adb     : udp_socket.cpp:274 SetMulticastOutboundInterface for index=2
02-02 14:47:39.386 30220 30220 I adb     : udp_socket.cpp:533 bind endpoint=0.0.0.0:5353
02-02 14:47:39.386 30220 30220 I adb     : udp_socket.cpp:274 SetMulticastOutboundInterface for index=2
02-02 14:47:39.386 30220 30220 I adb     : udp_socket.cpp:558 bind endpoint=[0000:0000:0000:0000:0000:0000:0000:0000]:5353 scope_id=0
02-02 14:47:39.386 30220 30220 I adb     : udp_socket.cpp:170 AdbUdpSocket fd=17
02-02 14:47:39.386 30220 30220 I adb     : udp_socket.cpp:274 SetMulticastOutboundInterface for index=3
02-02 14:47:39.386 30220 30220 I adb     : udp_socket.cpp:533 bind endpoint=0.0.0.0:5353
02-02 14:47:39.386 30220 30220 I adb     : udp_socket.cpp:170 AdbUdpSocket fd=18
02-02 14:47:39.386 30220 30220 I adb     : udp_socket.cpp:274 SetMulticastOutboundInterface for index=4
02-02 14:47:39.386 30220 30220 I adb     : udp_socket.cpp:533 bind endpoint=0.0.0.0:5353
02-02 14:47:39.386 30220 30220 I adb     : udp_socket.cpp:170 AdbUdpSocket fd=19
02-02 14:47:39.386 30220 30220 I adb     : udp_socket.cpp:274 SetMulticastOutboundInterface for index=5
02-02 14:47:39.386 30220 30220 I adb     : udp_socket.cpp:533 bind endpoint=0.0.0.0:5353
02-02 14:47:40.385 30220 30220 E adb     : usb_libusb.cpp:598 failed to open device: Access denied (insufficient permissions)
02-02 14:47:40.385 30220 30220 I adb     : transport.cpp:1153 27191FDH2000B1: connection terminated: failed to open device: Access denied (insufficient permissions)

* failed to start daemon
adb: unable to connect for root: cannot connect to daemon

**Comment by jordanss1** [comment]
nevermind never had to run adb as sudo before, weird...

> adb root        
adbd cannot run as root in production builds

After realising I couldn't downgrade I did patch the alpha build and try that. Don't know if that ha something to do with it?

**Comment by pixincreate** [comment]
the reason why i asked whether you can execute `adb root` is that, magisk, from what i remember used to grant root access to `shell` which basically enabled user to execute `adb root`.  

this was one of the hint that magisk is broken on grapheneos.

**Comment by jordanss1** [comment]
It was working on the latest grapheneos build until I did something to mess it up. So you're saying it's broken altogether?

**Comment by pixincreate** [comment]
can you tell me the version?

at least, for me, zygisk as a whole has been broken since like october 2023 or so. and couldn't access root from the app since around march 2024.

and yes, i'm now using grapheneos with locked bootloader without root. so not sure, what's going on in there!

**Comment by jordanss1** [comment]
I am currently using alpha 2025020200 but before that i was using 2025012700. Wow, I have had rooted graphene forever this is the first issue I've encountered this and I think it's my fault. 

Is there a way I could install the previous version without getting the 'denying OTA SPL Downgrade' error? I'm scared I'll end up having to wipe and start over to fix this.

**Comment by pixincreate** [comment]
you cannot downgrade from what i know.

**Comment by chenxiaolong** [comment]
Magisk (excluding Zygisk) should still work on the latest version of GrapheneOS. I'll verify that on my test device today.

Just to confirm: is the Magisk app version definitely the same as what you used to patch the OTA? And what was the original version of Magisk you had installed and the version you have installed now?

---

As long as you can still flash OTAs, this is recoverable. Worst case, we can include a boot script in the OTA so that it resets Magisk's settings on boot.

**Comment by jordanss1** [comment]
Yes it does work on latest Graphene I've just verified it. 

I just chose to wipe and start fresh as I had no idea what the issue was. I figured it out now I believe though. I swapped to a different version of magisk and didn't realize the preinit partition was different. It was either that or when I started the magisk app I updated to a later version. Probably the latter tbh. 

What would have been the fix for this scenario? As I lost all root on device. I tried re-sideloading multiple times afterwards with the correct magisk version and it still wouldn't budge :(

**Comment by jordanss1** [comment]
Also, could it have been accepting the 'Requires Additional Setup' prompt from Magisk that caused the issue? I'd imagine not but worth asking

**Comment by chenxiaolong** [comment]
Sorry you had to wipe, but glad it's working again!

> What would have been the fix for this scenario? As I lost all root on device. I tried re-sideloading multiple times afterwards with the correct magisk version and it still wouldn't budge :(

> Also, could it have been accepting the 'Requires Additional Setup' prompt from Magisk that caused the issue? I'd imagine not but worth asking

Yep, it was very likely the "Requires Additional Setup" that caused the issue. I don't know what exactly breaks, but I've seen this reported many times, both from people who use avbroot and people who don't. I'm guessing there's some sort of data migration bug that sometimes happens, but I don't know for sure since I haven't encountered this myself.

The preinit partition shouldn't be an issue. A wrong value there may break some modules, but the basic `su` functionality does not depend on it.

Magisk stores all of its state in `/data/adb`. This includes all the modules, Magisk's binaries (what's updated during "Requires Additional Setup"), and Magisk's settings. It's likely the issue could have been fixed by flashing a temporary OTA that runs `rm -rf /data/adb` on boot and then flashing a normal OTA again.

**Comment by jordanss1** [comment]
It's all good, sucks but at least it works! 

Ahh man I just accepted the prompt again after finding out Magisk still isn't working in work profile again. Any idea why root isn't recognized in work profile? Cloning Magisk to it is showing as it's not installed there. Before all this it was working perfectly!
